In [25]:
import pandas as pd

In [30]:
df= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,China,2020-03-17T11:53:10,67799,3111,56003,30.9756,112.2707
1,NaN,Italy,2020-03-17T18:33:02,31506,2503,2941,41.8719,12.5674
2,NaN,Iran,2020-03-17T15:13:09,16169,988,5389,32.4279,53.6880
3,NaN,Spain,2020-03-17T20:53:02,11748,533,1028,40.4637,-3.7492
4,NaN,Germany,2020-03-17T18:53:02,9257,24,67,51.1657,10.4515
...,...,...,...,...,...,...,...,...
307,Wales,United Kingdom,2020-03-17T11:53:10,0,5,0,52.1307,-3.7837
308,NaN,Nauru,2020-03-17T11:53:10,0,0,0,-0.5228,166.9315
309,Niue,New Zealand,2020-03-17T11:53:10,0,0,0,-19.0544,-169.8672
310,NaN,Tuvalu,2020-03-17T11:53:10,0,0,0,-7.1095,177.6493
311,Pitcairn Islands,United Kingdom,2020-03-17T11:53:10,0,0,0,-24.3768,-128.3242

1. Write a Python program to display first 5 rows from COVID-19 dataset. Also print the dataset information and check the missing values.

In [32]:
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,China,2020-03-17T11:53:10,67799,3111,56003,30.9756,112.2707
1,NaN,Italy,2020-03-17T18:33:02,31506,2503,2941,41.8719,12.5674
2,NaN,Iran,2020-03-17T15:13:09,16169,988,5389,32.4279,53.6880
3,NaN,Spain,2020-03-17T20:53:02,11748,533,1028,40.4637,-3.7492
4,NaN,Germany,2020-03-17T18:53:02,9257,24,67,51.1657,10.4515

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  154 non-null    object
 1   Country/Region  312 non-null    object
 2   Last Update     312 non-null    object
 3   Confirmed       312 non-null    int64
 4   Deaths          312 non-null    int64
 5   Recovered       312 non-null    int64
 6   Latitude        309 non-null    float64
 7   Longitude       309 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 19.6+ KB

In [34]:
df.isnull().sum()

Province/State    158
Country/Region      0
Last Update         0
Confirmed           0
Deaths              0
Recovered           0
Latitude            3
Longitude           3
dtype: int64

In [42]:
df[['Confirmed','Deaths','Recovered']]

     Confirmed  Deaths  Recovered
0        67799    3111      56003
1        31506    2503       2941
2        16169     988       5389
3        11748     533       1028
4         9257      24         67
..         ...     ...        ...
307          0       5          0
308          0       0          0
309          0       0          0
310          0       0          0
311          0       0          0

[312 rows x 3 columns]

In [45]:
df.groupby('Country/Region')[['Confirmed','Deaths','Recovered']].sum()

                                Confirmed  Deaths  Recovered
Country/Region
Afghanistan                            26       0          1
Albania                                55       1          0
Algeria                                60       4         12
Andorra                                39       0          1
Antarctica                              0       0          0
...                                   ...     ...        ...
Uzbekistan                             10       0          0
Venezuela                              33       0          0
Vietnam                                66       0         16
Winter Olympics 2022                    0       0          0
occupied Palestinian territory          0       0          0

[168 rows x 3 columns]

In [47]:
df.groupby(['Country/Region','Province/State'])[['Confirmed','Deaths','Recovered']].max()

                                             Confirmed  Deaths  Recovered
Country/Region Province/State
Australia      Australian Capital Territory          2       0          0
               From Diamond Princess                 0       0          0
               New South Wales                     210       4          4
               Northern Territory                    1       0          0
               Queensland                           78       0          8
...                                                ...     ...        ...
United Kingdom Northern Ireland                      0       0          0
               Pitcairn Islands                      0       0          0
               Scotland                              0      11          0
               Unknown                            1950       2         52
               Wales                                 0       5          0

[154 rows x 3 columns]

4. Write a Python program to get the Chinese province wise cases of confirmed, deaths and recovered cases of Novel Coronavirus (COVID-19).

In [53]:
df[df['Country/Region'] == 'China'].groupby(['Province/State'])[['Confirmed','Deaths','Recovered']].max()

                Confirmed  Deaths  Recovered
Province/State
Anhui                 990       6        984
Beijing               456       8        369
Chongqing             576       6        570
Fujian                296       1        295
Gansu                 133       2         91
Guangdong            1364       8       1307
Guangxi               253       2        248
Guizhou               147       2        144
Hainan                168       6        161
Hebei                 318       6        310
Heilongjiang          482      13        456
Henan                1273      22       1250
Hong Kong             162       4         88
Hubei               67799    3111      56003
Hunan                1018       4       1014
Inner Mongolia         75       1         73
Jiangsu               631       0        631
Jiangxi               935       1        934
Jilin                  93       1         92
Liaoning              125       1        120
Macau                  12       0         10
Ningxia                75       0         75
Qinghai                18       0         18
Shaanxi               246       3        236
Shandong              761       7        746
Shanghai              358       3        325
Shanxi                133       0        133
Sichuan               540       3        520
Tianjin               136       3        133
Tibet                   1       0          1
Unknown                 0       0          0
Xinjiang               76       3         73
Yunnan                176       2        172
Zhejiang             1232       1       1216

6. Write a Python program to list countries with no cases of Novel Coronavirus (COVID-19) recovered.

In [57]:
df[df['Recovered'] == 0]['Country/Region'].unique()

array(['US', 'Slovenia', 'Iceland', 'Chile', 'Luxembourg', 'Canada',
       'Slovakia', 'Panama', 'Bulgaria', 'South Africa', 'Ecuador',
       'Brunei', 'Albania', 'Denmark', 'Turkey', 'Cyprus', 'Costa Rica',
       'Kazakhstan', 'Venezuela', 'Australia', 'Uruguay', 'Tunisia',
       'Dominican Republic', 'Guadeloupe', 'Martinique', 'Burkina Faso',
       'Ukraine', 'Maldives', 'New Zealand', 'Bolivia', 'French Guiana',
       'Cameroon', 'Uzbekistan', 'France', 'Paraguay', 'Reunion',
       'Honduras', 'Ghana', 'Guyana', 'Liechtenstein', 'Monaco', 'Rwanda',
       'Guatemala', 'United Kingdom', 'Cuba', 'Ethiopia', 'Mongolia',
       'Trinidad and Tobago', 'Seychelles', 'Aruba', 'Congo (Kinshasa)',
       'Guam', 'Kenya', 'Netherlands', 'Nigeria', 'Barbados', 'Kosovo',
       'Montenegro', 'Namibia', 'Saint Lucia', 'Antigua and Barbuda',
       'Benin', 'Bhutan', 'Central African Republic',
       'Congo (Brazzaville)', 'Equatorial Guinea', 'Eswatini', 'Gabon',
       'Greenland', 'Guinea', 'Holy See', 'Liberia', 'Mauritania',
       'Mayotte', 'Saint Vincent and the Grenadines', 'Somalia', 'Sudan',
       'Suriname', 'Tanzania', 'The Bahamas', 'The Gambia', 'Togo',
       'Guernsey', 'Jersey', 'Puerto Rico', 'Republic of the Congo',
       'occupied Palestinian territory', 'China', 'Kiribati', 'Palau',
       'Summer Olympics 2020', 'Malaysia', 'Tonga',
       'Winter Olympics 2022', 'Antarctica', 'Korea, North', 'Nauru',
       'Tuvalu'], dtype=object)