In [2]:
%%writefile x.csv
Year,WHO region,Country,Beverage Types,Display Value
1986,Western Pacific,Viet Nam,Wine,0
1986,Americas,Uruguay,Other,0.5
1985,Africa,Cte d'Ivoire,Wine,1.62
1986,Americas,Colombia,Beer,4.27
1987,Americas,Saint Kitts and Nevis,Beer,1.98
1987,Americas,Guatemala,Other,0
1987,Africa,Mauritius,Wine,0.13
1985,Africa,Angola,Spirits,0.39
1986,Americas,Antigua and Barbuda,Spirits,1.55
1984,Africa,Nigeria,Other,6.1
1987,Africa,Botswana,Wine,0.2
1989,Americas,Guatemala,Beer,0.62
1985,Western Pacific,Lao People's Democratic Republic,Beer,0
1984,Eastern Mediterranean,Afghanistan,Other,0
1985,Western Pacific,Viet Nam,Spirits,0.05
1987,Africa,Guinea-Bissau,Wine,0.07
1984,Americas,Costa Rica,Wine,0.06
1989,Africa,Seychelles,Beer,2.23
1984,Europe,Norway,Spirits,1.62
1984,Africa,Kenya,Beer,1.08
1986,South-East Asia,Myanmar,Wine,0
1989,Americas,Costa Rica,Spirits,4.51
1984,Europe,Romania,Spirits,2.67
1984,Europe,Turkey,Beer,0.44
1985,Africa,Comoros,Other,
1984,Eastern Mediterranean,Tunisia,Other,0
1985,Europe,United Kingdom of Great Britain and Northern Ireland,Wine,1.36
1984,Eastern Mediterranean,Bahrain,Beer,2.22
1987,Western Pacific,Viet Nam,Beer,0.11
1986,Europe,Italy,Other,
1986,Africa,Sierra Leone,Other,4.48
1986,Western Pacific,Micronesia (Federated States of),Wine,0
1989,Africa,Mauritius,Beer,1.6
1985,Africa,Mauritania,Other,0
1986,Europe,Russian Federation,Wine,0.8
1985,Americas,Saint Kitts and Nevis,Spirits,2.24
1987,Eastern Mediterranean,Egypt,Beer,0.07
1986,Europe,Sweden,Beer,3.04
1987,Eastern Mediterranean,Qatar,Other,0
1987,Africa,Burkina Faso,Spirits,0.01
1987,Europe,Austria,Spirits,1.9
1986,Europe,Czech Republic,Beer,6.82
1984,Europe,Ukraine,Spirits,3.06
1984,Western Pacific,China,Wine,0.03
1985,Europe,Lithuania,Other,
1989,Africa,Zimbabwe,Beer,0.19
1987,Americas,Trinidad and Tobago,Spirits,2.26
1986,Americas,Mexico,Other,0.04
1987,Americas,Nicaragua,Beer,0.7
1986,Europe,Malta,Wine,1.49
1985,Europe,Switzerland,Other,0.3
1987,Europe,Finland,Beer,3.88
1986,Eastern Mediterranean,Saudi Arabia,Wine,0
1984,Eastern Mediterranean,Kuwait,Beer,0
1984,Americas,El Salvador,Spirits,1.81
1989,Americas,Suriname,Wine,0.04
1987,Western Pacific,Viet Nam,Wine,0
1989,Europe,Croatia,Wine,5.1
1984,Eastern Mediterranean,Somalia,Spirits,0
1989,Eastern Mediterranean,Syrian Arab Republic,Other,0
1987,Eastern Mediterranean,Iran (Islamic Republic of),Other,0
1984,Western Pacific,Papua New Guinea,Spirits,0.08
1987,Americas,Suriname,Other,0
1985,Eastern Mediterranean,Libya,Other,0
1989,Americas,Bolivia (Plurinational State of),Beer,1.26
1989,Eastern Mediterranean,Somalia,Beer,0
1987,Eastern Mediterranean,Iraq,Wine,0.01
1989,Africa,Namibia,Beer,0
1989,Africa,Uganda,Beer,0.12
1986,Africa,Togo,Spirits,0.42
1986,Africa,Madagascar,Spirits,1.02
1985,Africa,Mali,Other,0.57
1987,Africa,Mauritania,Other,0
1986,Eastern Mediterranean,Pakistan,Other,0.01
1986,Americas,Bolivia (Plurinational State of),Spirits,2.06
1989,Eastern Mediterranean,Afghanistan,Other,0
1985,Africa,Comoros,Beer,0.02
1985,Africa,Cameroon,Spirits,0.01
1989,Americas,Jamaica,Other,0
1989,Europe,Finland,Other,2.09
1985,Africa,Malawi,Other,0.84
1985,Europe,Netherlands,Wine,2.54
1987,Europe,Ireland,Spirits,2.25
1986,Europe,Ukraine,Other,
1986,South-East Asia,Sri Lanka,Other,0
1985,Africa,Democratic Republic of the Congo,Wine,0.01
1986,Americas,Bahamas,Wine,1.83
1989,Eastern Mediterranean,Iraq,Wine,0.01
1987,Eastern Mediterranean,Lebanon,Beer,0.42
1986,Eastern Mediterranean,Lebanon,Wine,0.7
1989,Africa,Malawi,Wine,0.01
1989,Europe,Bulgaria,Beer,4.43
1986,Africa,Eritrea,Spirits,0
1987,Africa,Madagascar,Other,
1985,Europe,Ukraine,Spirits,3.06
1984,Africa,Niger,Other,0
1985,Europe,Luxembourg,Wine,7.38
1984,South-East Asia,Indonesia,Wine,0
1984,Africa,Equatorial Guinea,Wine,0
1985,South-East Asia,Democratic People's Republic of Korea,Wine,0

Writing x.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('x.csv')
df.head()

   Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            100 non-null    int64
 1   WHO region      100 non-null    object
 2   Country         100 non-null    object
 3   Beverage Types  100 non-null    object
 4   Display Value   95 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

In [8]:
df.shape

(100, 5)

In [9]:
df.columns

Index(['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'], dtype='object')

In [10]:
df.iloc[0:2,0:2]

   Year       WHO region
0  1986  Western Pacific
1  1986         Americas

In [11]:
df.iloc[0:2,[2,4]]

    Country  Display Value
0  Viet Nam            0.0
1   Uruguay            0.5

In [15]:
df = pd.read_excel('SaleData.xlsx')
df.head()

,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0

In [17]:
df.pivot_table(index='Region', columns=['Item'], values='Units')

Item     Cell Phone  Desk  Home Theater  Television  Video Games
Region
Central   27.000000   3.5          53.0   55.333333    60.750000
East      58.333333   NaN          46.8   65.000000    50.666667
West      76.000000   3.0          32.0   44.000000          NaN

In [23]:
import numpy as np

In [25]:
df.pivot_table(index='Region', columns=['Manager'], values='Sale_amt', aggfunc=np.sum)

C:\Users\PiyushChunara\AppData\Local\Temp\ipykernel_24136\923410416.py:1: FutureWarning: The provided callable <function sum at 0x000001B23AB88220> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index='Region', columns=['Manager'], values='Sale_amt', aggfunc=np.sum)

Manager   Douglas   Hermann    Martha   Timothy
Region
Central  124016.0  365108.5  199690.0  140955.0
East      48204.0       NaN  272803.0       NaN
West      66836.0       NaN       NaN   88063.0